- id: doi:10.1093/database/baac042
  type: paper
  date: 2022-1-1
  image: images/Mining Host-Pathogen Interactions from Biomedical Literature.jpg
  
- id: doi:10.1016/j.ijmedinf.2020.104351
  type: paper
  date: 2021-3-1
  image: images/A comprehensive study of mobility related function in clinical notes.jpg

- id: doi:10.1186/s12889-019-7630-3
  type: paper
  date: 2019-10-1
  image: images/Broadening horizons- the case for capturing function.jpeg
  
- id: doi:10.1093/bioinformatics/bts042
  type: paper
  date: 2012-1-27
  image: images/Literature mining of host–pathogen interactions- comparing feature-based supervised learning and language-based approaches.jpeg
  
- id: doi:10.1109/chase52844.2021.00024
  type: paper
  date: 2021-12-1
  image: images/A high-throughput, online tool-0000.jpg
